environment: development
port: 8080
log_level: info

database:
  host: localhost
  port: 5432
  user: postgres
  password: your_password
  dbname: guild_score
  sslmode: disable

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

subgraph_url: "http://localhost:8000/subgraphs/name/scaffold-eth/your-contract"
blockchain_rpc: "http://localhost:8545"

jwt_secret: "your-secret-key-change-in-production"

ai:
  python_service_url: "http://localhost:5000"
  model_path: "./models"